[project]
name = "python-module-template"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pmt = "pmt.main:main"

[dependency-groups]
dev = [
    "coverage>=7.13.2",
    "pytest>=9.0.3",
    "pytest-cov>=7.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"